<h2 class="paprotki"><strong>Udręczone paprotki <small>historia prawdziwa</small></strong></h2>
<p class="paprotki">W sali nr 6 gimnazjum nr 1 im. marszałka Józefa Piłsudskiego uczniowie NOTORYCZNIE podskubują kwiatki - kto wie? Może dlatego są takie marne?</p>
<p class="paprotki">Zaistniały problem niestety rozrasta się, wręcz kwitnie niczym dobry interes - czy nim jest? Listków na łodyżkach zaczyna brakować także w innych salach, a nawet na szkolnych korytarzach. rośliny marnieją, a zamiast nich... uczniowie sadzą 5 groszy!</p>
<p class="paprotki">Do czego dochodzi w dzisiejszych czasach? Czyżby Polska tak zbiedniała, że musimy sadzić pieniądze? A nie tylko paprotki na tym cierpią - a dusznych klasach nikt sam z siebie tlenu nie naprodukuje.</p>
<p class="paprotki">Sami uczniowie pewnie nie wiedzą, że sobie szkodzą, jednak idea wyhodowania własnego krzaczka pieniężnego mimo wszystko pozostaje szalenie kusząca...</p>
<p class="paprotki">Tak więc, co z tego, że nauczyciele łapią się za głowy i rwą włosy nad poczynaniami uczniów? Co z tego, że na każdym kroku ich upominają?</p>
<p class="paprotki">UCZEŃ WIE JEDNO - o takie 5 groszy to trzeba umieć zadbać, coby dobrze urosło. Z tego tytułu nasza przesławna moneta od czasu do czasu do towarzystwa ma kiełki rzeżuchy, również amatorsko uprawianej przez uczniów na szkolnym parapecie...</p>
